from mysql.connector import errorcode
import import_logger

logger =  import_logger.logIt(__file__)
#DEFINED ALL THE CONSTANTS THAT ARE USED IN THE PROGRAM


#DEFAULT VALUES GIVEN TO THE VALUES
_host 	  = "localhost"
_user	  = "testuser"
_pass	  = "testpassword"
_database = "tdb"



message_to_users = "To run this script you must already have a user and a database by the name railDB" 

class constData:
	'This class must be availabe to only the admin and developers'
	_DICT_ALLDATABASES_ = {
		"STUDENTS_DB"		:	"students",
		"TEMPORARY_DB"		:	"temp_data",
		"PROJECTS_DB"		:	"projects",
		"TEAMS_DB"			:	"teams"
	}

	#**********TABLE NAMES**********
	_DICT_ALLTABLES_ = {
		"STUDENT_DETAILS_TABLE" 	: "students", #TO STORE THE DETAILS OF THE REGISTERED STUDENTS
		"STUDENT_ATTENDANCE_TABLE"	: "students_attendence", #TO MONITOR THE ATTENDANCE OF STUDENTS
		"COMPONENTS_TABLE"			: "components", #TO STORE ALL THE COMPONENETS AVAILABLE
		"ADMIN_DETAILS_TABLE"		: "admin_details", #TO STORE ALL THE MENTORS AND ADMINS OF RAIL	
		"PROJECTS_OF_RAIL_TABLE"	: "rail_projects",
		"TEAMS_OF_RAIL"				: "rail_teams"
	}



	#**********TABLE HEADER NAMES**********
	#FOR STUDENT_DETAILS_TABLE ->
	_DICT_STUDENTS ={
		"SERIAL_NUMBER_HEADER"				: "slno", 
		"RAIL_ID_HEADER"					: "rail_id", #HEADER FOR RAIL ID
		"NAME_HEADER" 						: "student_name", #HEADER FOR STUDENT NAME
		"GENDER_HEADER"						: "gender", #HEADER FOR GENDER
		"DATE_OF_BIRTH_HEADER"				: "date_of_birth", #HEADER FOR DATE OF BIRTH
		"TIME_OF_JOINING_RAIL"				: "time_of_joining_rail",
		"PHONE_NUMBER_HEADER"				: "phone_number", #HEADER FOR PHONE NUMBER
		"EMAIL_HEADER"						: "email",
		"ASSOCIATED_TEAM_HEADER"			: "associated_team", #HEADER FOR ASSOCIATED TEAM
		"PROJECTS_DONE_HEADER"				: "projects_done",
		"BRANCH_HEADER"						: "branch", #HEADER FOR BRANCH
		"LOGIN_STATUS_HEADER"				: "login_status", #HEADER FOR LOGIN STATUS
		"COMPONENT_STATUS_HEADER"			: "component_status", #HEADER FOR COMPONENT STATUS
		"USN_HEADER"						: "usn", #HEADER FOR USN
		"TIME_SPENT_IN_RAIL_HEADER"			: "time_in_rail", #HEADER FOR DATE OF ACCOUNT CREATION
		"HIGHEST_ROLE_HEADER"				: "current_highest_role"
	}



	#FOR STUDENT_ATTENDANCE_TABLE ->
	_DICT_ATTENDENCE ={	
		"RAIL_ID_HEADER"		: "rail_id", #HEADER FOR RAIL ID
		"NAME_HEADER" 			: "student_name", #HEADER FOR STUDENT NAME
		"CURRENT_TEAM_HEADER"	: "current_team", #HEADER FOR ASSOCIATED TEAM
		"TIME_IN_HEADER"		: "time_in", #HEADER FOR TIME IN
		"TIME_OUT_HEADER"		: "time_out", #HEADER FOR TIME OUT
		"PURPOSE_HEADER"		: "purpose" #HEADER FOR PURPOSE OF COMING TO RAIL
	}


	_DICT_PROJECT	={
		"SERIAL_NUMBER_HEADER"			:	"slno",
		"PROJECT_NAME_HEADER"			:	"project_name",
		"ASSOCIATED_TEAM_HEADER"		:	"associated_team",
		"DESCRIPTION_HEADER"			:	"project_description",
		"NUMBER_OF_MEMBERS_HEADER"		:	"number_of_members",
		"MENTOR_NAME_HEADER"			:	"mentor",
		"TEAM_LEAD_HEADER"				:	"team_lead",
		"GUIDE_HEADER"					:	"guide",
		"IDEA_BY_HEADER"				:	"idea_by",
		"TYPE_OF_PROJECT_HEADER"		:	"type_of_project",
		"EXPECTED_DURATION_HEADER"		:	"expected_duration",
		"DATE_OF_PROJECT_START"			:	"date_start",
		"DATE_OF_PROJECT_END"			:	"date_end",
		"STATUS_HEADER"					:	"status",
		"PRIORITY_HEADER"				:	"priority",
		"TECHNOLOGY_STACK_HEADER"		:	"technology_stack"
	}

	_DICT_TEAMS	={
		"SERIAL_NUMBER_HEADER"			:	"slno",
		"TEAM_NAME_HEADER"				:	"team_name",
		"ASSOCIATED_PROJECTS_HEADER"	:	"associated_projects",
		"NUMBER_OF_MEMBERS_HEADER"		:	"number_of_members",
		"MEMBERS_HEADER"				:	"team_members",
		"DATE_OF_TEAM_CREATION_HEADER"	:	"date_of_team_creation"
	}

	_DICT_COMPONENTS ={
		"SERIAL_NUMBER_HEADER"	:	"slno",
		"ID_HEADER"				:	"component_id",
		"NAME_HEADER"			:	"component_name",
		"STATUS_HEADER"			:	"component_status",
		"GROUP_HEADER"			:	"component_group",
		"IF_KIT_HEADER"			:	"if_kit",
		"COLOR_CODE_HEADER"		:	"color_code"
	}

	#FOR ADMIN_DETAILS_TABLE ->
	_DICT_ADMIN = {	
		"SERIAL_NUMBER_HEADER"				: "slno",
		"ADMIN_NAME_HEADER"					: "admin_name", #HEADER FOR NAME OF ADMIN
		"ADMIN_ID_HEADER"					: "admin_id", #HEADER FOR ADMIN ID
		"DATE_OF_BIRTH_HEADER"				: "date_of_birth", #HEADER FOR DATE OF BIRTH
		"DATE_OF_ACCOUNT_CREATION_HEADER"	: "date_of_account_creation", #HEADER FOR ACCOUNT CREATION
		"PHONE_NUMBER_HEADER"				: "phone_number", #HEADER FOR PHONE NUMBER
		"EMAIL_HEADER"						: "email", #HEADER FOR EMAIL
		"PASSWORD_HEADER"					: "password" #HEADER FOR PASSWORD
	}


	#Dictionary for all the queries
	_DICT_STUDENTS_QUERY={
		_DICT_STUDENTS["SERIAL_NUMBER_HEADER"]		: "INT NOT NULL AUTO_INCREMENT",
		_DICT_STUDENTS["RAIL_ID_HEADER"]			: "CHAR(10) NOT NULL",
		_DICT_STUDENTS["NAME_HEADER"]				: "VARCHAR(50) NOT NULL", 
		_DICT_STUDENTS["GENDER_HEADER"]				: "CHAR(1)", #LATER MAKE THIS NOT NULL
		_DICT_STUDENTS["DATE_OF_BIRTH_HEADER"]		: "DATE", #LATER MAKE THIS NOT NULL
		_DICT_STUDENTS["TIME_OF_JOINING_RAIL"]		: "DATETIME DEFAULT NOW()",
		_DICT_STUDENTS["PHONE_NUMBER_HEADER"]		: "VARCHAR(10) NOT NULL", 
		_DICT_STUDENTS["EMAIL_HEADER"]				: "VARCHAR(40) NOT NULL",
		_DICT_STUDENTS["ASSOCIATED_TEAM_HEADER"]	: "VARCHAR(20)", #LATER MAKE THIS NOT NULL
		_DICT_STUDENTS["PROJECTS_DONE_HEADER"]		: "INT DEFAULT 0",
		_DICT_STUDENTS["BRANCH_HEADER"]				: "VARCHAR(5) NOT NULL",
		_DICT_STUDENTS["LOGIN_STATUS_HEADER"]		: "VARCHAR(3) DEFAULT 'NO'",
		_DICT_STUDENTS["COMPONENT_STATUS_HEADER"]	: "VARCHAR(3) DEFAULT 'NO'",
		_DICT_STUDENTS["USN_HEADER"]				: "CHAR(10) NOT NULL",
		_DICT_STUDENTS["TIME_SPENT_IN_RAIL_HEADER"]	: "TIME",
		_DICT_STUDENTS["HIGHEST_ROLE_HEADER"]		: "TEXT",
		"PRIMARY KEY"								: _DICT_STUDENTS["SERIAL_NUMBER_HEADER"]
	}

	_DICT_STUDENTS_ATTENDENCE_QUERY	={
		_DICT_ATTENDENCE["RAIL_ID_HEADER"]		: "VARCHAR(11) NOT NULL",
		_DICT_ATTENDENCE["NAME_HEADER"]			: "VARCHAR(50) NOT NULL",
		_DICT_ATTENDENCE["CURRENT_TEAM_HEADER"]	: "CHAR(1) NOT NULL",
		_DICT_ATTENDENCE["TIME_IN_HEADER"]		: "DATETIME DEFAULT NOW()",
		_DICT_ATTENDENCE["TIME_OUT_HEADER"]		: "DATETIME DEFAULT null",
		_DICT_ATTENDENCE["PURPOSE_HEADER"]		: "TEXT NOT NULL",
	}

	_DICT_PROJECT_QUERY	={
		_DICT_PROJECT["SERIAL_NUMBER_HEADER"]		: "INT NOT NULL AUTO_INCREMENT",
		_DICT_PROJECT["PROJECT_NAME_HEADER"]		: "TEXT NOT NULL",
		_DICT_PROJECT["ASSOCIATED_TEAM_HEADER"]		: "CHAR(1) NOT NULL",
		_DICT_PROJECT["DESCRIPTION_HEADER"]			: "TEXT NOT NULL",
		_DICT_PROJECT["NUMBER_OF_MEMBERS_HEADER"]	: "TINYINT NOT NULL",
		_DICT_PROJECT["MENTOR_NAME_HEADER"]			: "VARCHAR(50)",
		_DICT_PROJECT["TEAM_LEAD_HEADER"]			: "VARCHAR(50) NOT NULL",
		_DICT_PROJECT["GUIDE_HEADER"]				: "VARCHAR(50)",
		_DICT_PROJECT["IDEA_BY_HEADER"]				: "TEXT",
		_DICT_PROJECT["TYPE_OF_PROJECT_HEADER"]		: "TEXT",
		_DICT_PROJECT["EXPECTED_DURATION_HEADER"]	: "TEXT NOT NULL",
		_DICT_PROJECT["DATE_OF_PROJECT_START"]		: "DATETIME NOT NULL",
		_DICT_PROJECT["DATE_OF_PROJECT_END"]		: "DATETIME DEFAULT null",
		_DICT_PROJECT["STATUS_HEADER"]				: "TEXT NOT NULL",
		_DICT_PROJECT["PRIORITY_HEADER"]			: "TEXT NOT NULL",
		_DICT_PROJECT["TECHNOLOGY_STACK_HEADER"]	: "TEXT NOT NULL",
		"PRIMARY KEY"								: _DICT_PROJECT["SERIAL_NUMBER_HEADER"]
	}

	_DICT_TEAMS_QUERY ={
		_DICT_TEAMS["SERIAL_NUMBER_HEADER"]			: "INT NOT NULL AUTO_INCREMENT",
		_DICT_TEAMS["TEAM_NAME_HEADER"]				: "CHAR(2) NOT NULL",
		_DICT_TEAMS["ASSOCIATED_PROJECTS_HEADER"]	: "TEXT NOT NULL",
		_DICT_TEAMS["NUMBER_OF_MEMBERS_HEADER"]		: "TINYINT NOT NULL",
		_DICT_TEAMS["MEMBERS_HEADER"]				: "TEXT NOT NULL",
		_DICT_TEAMS["DATE_OF_TEAM_CREATION_HEADER"]	: "DATETIME DEFAULT NOW()",
		"PRIMARY KEY"								: _DICT_TEAMS["SERIAL_NUMBER_HEADER"]
	}

	_DICT_COMPONENTS_QUERY ={
		_DICT_COMPONENTS["SERIAL_NUMBER_HEADER"]	: "INT NOT NULL AUTO_INCREMENT",
		_DICT_COMPONENTS["ID_HEADER"]				: "CHAR(10) NOT NULL",
		_DICT_COMPONENTS["NAME_HEADER"]				: "TEXT NOT NULL",
		_DICT_COMPONENTS["STATUS_HEADER"]			: "CHAR(20) DEFAULT 'ADMIN'",
		_DICT_COMPONENTS["GROUP_HEADER"]			: "CHAR(20)",
		_DICT_COMPONENTS["IF_KIT_HEADER"]			: "VARCHAR(3) NOT NULL",
		_DICT_COMPONENTS["COLOR_CODE_HEADER"]		: "CHAR(6) NOT NULL",
		"PRIMARY KEY"								: _DICT_COMPONENTS["SERIAL_NUMBER_HEADER"]
	}

	_DICT_ADMIN_QUERY ={
		_DICT_ADMIN["SERIAL_NUMBER_HEADER"]				: "INT NOT NULL AUTO_INCREMENT",
		_DICT_ADMIN["ADMIN_NAME_HEADER"]				: "VARCHAR(50) NOT NULL",
		_DICT_ADMIN["ADMIN_ID_HEADER"]					: "VARCHAR(10) NOT NULL",
		_DICT_ADMIN["DATE_OF_BIRTH_HEADER"]				: "DATETIME DEFAULT null",
		_DICT_ADMIN["DATE_OF_ACCOUNT_CREATION_HEADER"]	: "DATETIME NOT NULL",
		_DICT_ADMIN["PHONE_NUMBER_HEADER"]				: "CHAR(10)",
		_DICT_ADMIN["EMAIL_HEADER"]						: "VARCHAR(50) NOT NULL",
		_DICT_ADMIN["PASSWORD_HEADER"]					: "VARCHAR(20) NOT NULL",
		"PRIMARY KEY"									: _DICT_ADMIN["SERIAL_NUMBER_HEADER"]
	}



	#DATA BEING SENT TO THE FRONT END
	_READ_LIST = (
		_DICT_STUDENTS["RAIL_ID_HEADER"],	#This must always be on top
		_DICT_STUDENTS["NAME_HEADER"],
		_DICT_STUDENTS["PHONE_NUMBER_HEADER"],
		_DICT_STUDENTS["BRANCH_HEADER"],
		_DICT_STUDENTS["ASSOCIATED_TEAM_HEADER"],
		_DICT_STUDENTS["LOGIN_STATUS_HEADER"],
		_DICT_STUDENTS["COMPONENT_STATUS_HEADER"]
	)

	_READ_EACH_LIST = (
		_DICT_STUDENTS["RAIL_ID_HEADER"],	#This must always be on top
		_DICT_STUDENTS["NAME_HEADER"],
		_DICT_STUDENTS["GENDER_HEADER"],
		_DICT_STUDENTS["DATE_OF_BIRTH_HEADER"],
		_DICT_STUDENTS["TIME_OF_JOINING_RAIL"],
		_DICT_STUDENTS["PHONE_NUMBER_HEADER"],
		_DICT_STUDENTS["EMAIL_HEADER"],
		_DICT_STUDENTS["USN_HEADER"],
		_DICT_STUDENTS["BRANCH_HEADER"],
		_DICT_STUDENTS["ASSOCIATED_TEAM_HEADER"],
		_DICT_STUDENTS["LOGIN_STATUS_HEADER"],
		_DICT_STUDENTS["COMPONENT_STATUS_HEADER"],
	)

	_READ_ATTENDENCE_LIST = (
		_DICT_ATTENDENCE["RAIL_ID_HEADER"],	#This must always be on top
		_DICT_ATTENDENCE["NAME_HEADER"],
		_DICT_ATTENDENCE["CURRENT_TEAM_HEADER"],
		_DICT_ATTENDENCE["TIME_IN_HEADER"],
		_DICT_ATTENDENCE["TIME_OUT_HEADER"],
		_DICT_ATTENDENCE["PURPOSE_HEADER"]
	)

	_READ_PROJECTS_LIST = (
		_DICT_PROJECT["PROJECT_NAME_HEADER"],
		_DICT_PROJECT["SERIAL_NUMBER_HEADER"],
		_DICT_PROJECT["ASSOCIATED_TEAM_HEADER"],
		_DICT_PROJECT["DESCRIPTION_HEADER"],
		_DICT_PROJECT["NUMBER_OF_MEMBERS_HEADER"],
		_DICT_PROJECT["MENTOR_NAME_HEADER"],
		_DICT_PROJECT["TEAM_LEAD_HEADER"],
		_DICT_PROJECT["GUIDE_HEADER"],
		_DICT_PROJECT["IDEA_BY_HEADER"],
		_DICT_PROJECT["TYPE_OF_PROJECT_HEADER"],
		_DICT_PROJECT["EXPECTED_DURATION_HEADER"],
		_DICT_PROJECT["DATE_OF_PROJECT_START"],
		_DICT_PROJECT["DATE_OF_PROJECT_END"],
		_DICT_PROJECT["STATUS_HEADER"],
		_DICT_PROJECT["PRIORITY_HEADER"],
		_DICT_PROJECT["TECHNOLOGY_STACK_HEADER"]
	)

	_READ_COMPONENTS_LIST = (
		_DICT_COMPONENTS["ID_HEADER"],
		_DICT_COMPONENTS["NAME_HEADER"],
		_DICT_COMPONENTS["STATUS_HEADER"],
		_DICT_COMPONENTS["GROUP_HEADER"],
		_DICT_COMPONENTS["IF_KIT_HEADER"],
		_DICT_COMPONENTS["COLOR_CODE_HEADER"]
	)

	_READ_ADMIN_LIST =(
		_DICT_ADMIN["SERIAL_NUMBER_HEADER"],
		_DICT_ADMIN["ADMIN_NAME_HEADER"],
		_DICT_ADMIN["ADMIN_ID_HEADER"],
		_DICT_ADMIN["DATE_OF_BIRTH_HEADER"],
		_DICT_ADMIN["DATE_OF_ACCOUNT_CREATION_HEADER"],
		_DICT_ADMIN["PHONE_NUMBER_HEADER"],
		_DICT_ADMIN["EMAIL_HEADER"],
		_DICT_ADMIN["PASSWORD_HEADER"]
	)

	_READ_TEAMS_LIST = (
		_DICT_TEAMS["SERIAL_NUMBER_HEADER"],
		_DICT_TEAMS["TEAM_NAME_HEADER"],
		_DICT_TEAMS["ASSOCIATED_PROJECTS_HEADER"],
		_DICT_TEAMS["NUMBER_OF_MEMBERS_HEADER"],
		_DICT_TEAMS["MEMBERS_HEADER"],
		_DICT_TEAMS["DATE_OF_TEAM_CREATION_HEADER"]
	)
	
	_INDEX_LIST_STUDENTS = (
		_DICT_STUDENTS["SERIAL_NUMBER_HEADER"],
		_DICT_STUDENTS["RAIL_ID_HEADER"],
		_DICT_STUDENTS["PHONE_NUMBER_HEADER"],
		_DICT_STUDENTS["EMAIL_HEADER"],
		_DICT_STUDENTS["USN_HEADER"]
	)


	#IG I MIGHT USE THIS ONLY FOR TESTING PURPOSE
	#{}
	

	#MAPPED DICTIONARY
	mapped_tables = {	
						"1"	: 	_DICT_ALLTABLES_["STUDENT_DETAILS_TABLE"],
						"2"	:	_DICT_ALLTABLES_["STUDENT_ATTENDANCE_TABLE"],
						"3"	:	_DICT_ALLTABLES_["COMPONENTS_TABLE"],
						"4"	:	_DICT_ALLTABLES_["ADMIN_DETAILS_TABLE"],
						"5"	:	_DICT_ALLTABLES_["PROJECTS_OF_RAIL_TABLE"],
						"6"	:	_DICT_ALLTABLES_["TEAMS_OF_RAIL"]
					}

	def unmap(self,key):
		return self.mapped_tables[key]

